version: '2.1'

networks:
  test-net:

services:
  sut:
    build:
      context: ./simple_api
      dockerfile: Dockerfile
    command: /run_tests.sh
    volumes:
      - ./simple_api/student_age.json:/data/student_age.json
    networks:
      - test-net
