version: '2.1'
# we need to run test to validate the builded image
networks:
  test-net:

services:
  sut:
    build:
      context: .
      dockerfile: Dockerfile
    command: bash -c "nohup python /student_age.py & && /run_tests.sh" #/run_tests.sh
    volumes:
      - ./student_age.json:/data/student_age.json
    networks:
      - test-net
